<?php
/**
 * @category    Foggyline
 * @package     Foggyline_Cctoolbar
 * @copyright   Copyright (c) Branko Ajzele <ajzele@gmail.com>
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php $_helper = Mage::helper('foggyline_cctoolbar') ?>
<?php $_store = Mage::app()->getStore() ?>
<?php $attributeLabelMappings = $_helper->getAttributeLabelMappings() ?>
<?php if ($this->getCollection()->getSize()): ?>
    <div class="toolbar">
        <div class="pager">
            <p class="amount">
                <?php if ($this->getLastPageNum() > 1): ?>
                    <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                <?php else: ?>
                    <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                <?php endif; ?>
            </p>

            <div class="limiter">
                <label><?php echo $this->__('Show') ?></label>
                <select onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if ($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                    <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </div>

            <?php echo $this->getPagerHtml() ?>

        </div>

        <?php if ($this->isExpanded()): ?>
            <div class="sorter">
                <?php if ($this->isEnabledViewSwitcher()): ?>
                    <p class="view-mode">
                        <?php $_modes = $this->getModes(); ?>
                        <?php if ($_modes && count($_modes) > 1): ?>
                            <?php if (!$_helper->getHideViewAsLabel($_store)): ?><label><?php echo $this->__('View as') ?>:</label><?php endif; ?>
                            <?php foreach ($this->getModes() as $_code => $_label): ?>
                                <?php if ($this->isModeActive($_code)): ?>
                                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                                <?php else: ?>
                                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </p>
                <?php endif; ?>




                <div class="sort-by">
                    <?php if (!$_helper->getHideSortByLabel($_store)): ?><label><?php echo $this->__('Sort By') ?></label><?php endif; ?>
                    <select onchange="setLocation(this.value)">
                        <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
                            <?php $label = $this->__($_order) ?>
                            <?php $label2 = $label ?>
                            <?php if (array_key_exists($_key, $attributeLabelMappings)): ?>
                                <?php $label = $this->__($attributeLabelMappings[$_key][0], $_order) ?>
                                <?php $label2 = $this->__($attributeLabelMappings[$_key][1], $_order) ?>
                            <?php else: ?>
                                <?php $label = $this->__($_helper->getDefaultAscLabel($_store), $_order) ?>
                                <?php $label2 = $this->__($_helper->getDefaultDescLabel($_store), $_order) ?>                        
                            <?php endif; ?>
                            <?php if ($_helper->getMergeSortDir($_store)): ?>
                                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if ($this->isOrderCurrent($_key) && ($this->getCurrentDirection() == 'asc')): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $label ?>
                                </option>
                                <option value="<?php echo $this->getOrderUrl($_key, 'desc') ?>"<?php if ($this->isOrderCurrent($_key) && ($this->getCurrentDirection() == 'desc')): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $label2 ?>
                                </option>
                            <?php else: ?>
                                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                                    <?php echo $this->__($_order) ?>
                                </option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                    <?php if (!$_helper->getHideDirection($_store)): ?>
                        <?php if ($this->getCurrentDirection() == 'desc'): ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
                        <?php else: ?>
                            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><img src="<?php echo $this->getSkinUrl('images/i_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
